categories = [
    ["Play-1", "Objects that make a sound when played by a person through a string as a medium.", ['violin', 'cello', 'erhu fiddle', 'viola']],
    ["Play-2", "Objects that can interact directly with the hand to produce sound.", ['guitar', 'banjo', 'harp', 'pipa']],
    ["Play-3", "Objects that can produce sound by a person playing a keyboard.", ['piano', 'accordion', 'electric piano']],
    ["Play-4", "Objects that a person blows through their mouth to make a sound.", ['flute', 'trumpet', 'french horn', 'harmonica', 'cucurbit flute']],
    ["Take photo", "Objects that can take pictures of people.", ['camera']],
    ["Contain-1", "Containers that can hold a variety of household items and miscellaneous goods.", ['backpack', 'gift box', 'handbag', 'purse', 'shopping trolley', 'suitcase', 'storage box', 'pushchair']],
    ["Contain-2", "Objects that have the capable of containing a variety of liquids.", ['cup', 'bowl', 'beaker', 'pitcher', 'milk can', 'beer bottle', 'vase', 'soap dispenser', 'watering can']],
    ["Contain-3", "Containers that can be used to hold food.", ['bowl', 'frying pan', 'plate']],
    ["Scoop", "Objects that have the specific ability to scoop food up from the bottom.", ['spatula', 'spoon', 'soup ladle']],
    ["Wear-1", "Objects are worn on a person's head for decoration or protection.", ['hat', 'helmet']],
    ["Wear-2", "Objects with a combination of lenses and frames used to improve vision, or protect the eyes.", ['glasses']],
    ["Wear-3", "Objects are worn on the feet.", ['high heels', 'boots', 'slippers', 'sports shoes']],
    ["Wear-4", "Objects are worn on the hand for decoration, warmth or protection.", ['gloves']],
    ["Sit", "Objects that can be used to sit.", ['stool', 'sofa', 'bench', 'swing', 'wheelchair', 'rocking chair']],
    ["Cut", "Objects that have the ability to cut other objects.", ['knife', 'scissors']],
    ["Pick up", "Objects that have the function of holding food up.", ['chopsticks']],
    ["Brush", "Objects that can remove dirt or apply cosmetics.", ['toothbrush', 'broom', 'brushes', 'cosmetic brushes']],
    ["Ride", "Vehicles that can be used for riding.", ['bicycle', 'motorbike']],
    ["Kick", "Objects that can be kicked in direct contact with the foot.", ['soccer ball', 'punching bag', 'rugby ball']],
    ["Hit", "Indicates tools that can be used to strike other objects.", ['axe', 'hammer',  'baseball bat', 'hoe', 'rolling pin']],
    ["Beat", "Objects that can be played by beating a surface to produce a sound.", ['drum']],
    ["Jump", "Objects that allow rapid movement by allowing people to jump on surfaces.", ['snowboard', 'surfboard', 'skis', 'skateboard']],
    ["Swing", "Objects that a person interacts with by swinging their arm.", ['baseball bat', 'tennis racket', 'table tennis bat']],
    ["Lie", "Objects with a large surface space that allow a person to lie down.", ['sofa', 'baby bed', 'bench', 'pushchair', 'rocking chair']],
    ["Bounce", "Objects that can be slapped directly by a person's hand and bounced.", ['basketball', 'volleyball']],
    ["Mix", "Objects that can be used for mixing.", ['whisk', 'chopsticks', 'spoon', 'soup ladle', 'spatula']],
    ["Look out", "Objects that can be used for seeing at a distance.", ['binoculars']],
    ["Fork", "Indicates tools used to fork up food.", ['fork']],
    ["Shelter", "Objects that provide shade from the sun or rain.", ['umbrella']],
    ["Roll dough", "Objects that can be used to roll out dough.", ['rolling pin']],
    ["Rolling", "Objects that can be made to roll by hitting them through an intermediate medium.", ['table tennis ball', 'croquet ball', 'tennis ball', 'golf ball', 'baseball']],
    ["Lift", "Objects that are lifted and lowered for fitness purpose.", ['dumbbell']],
    ["Throw", "Objects that a person uses to throw.", ['frisbee', 'bowling', 'dart', 'javelin', 'basketball', 'weight throw', 'baseball', 'rugby ball']],
    ["Boxing", "Objects hit by boxing sports.", ['punching bag']],
    ["Push&Pull", "Objects with wheels below that can be pushed or pulled.", ['wheelchairs', 'bicycle', 'motorbike', 'suitcase', 'pushchair']],
    ["Crutches", "Objects that can play the function of assisting to walk people or stand.", ['crutch', 'umbrella']],
    ["Standing", "Objects that can be stepped on to reach a higher position.", ['stool', 'desk', 'bench', 'sofa']],
    ["Support", "Objects with a smooth surface that can hold various items.", ['desk']],
    ["Write", "Objects that can be used for writing.", ['pen', 'writing brush']],
]
